[package]
name = "nu_plugin_image"
version = "0.1.0"
edition = "2021"

[dependencies]
# The primary library used to interface with Nushell
nu-plugin = "0.115.1"
nu-protocol = "0.115.1"

# Excellent crate for jpg/png manipulation (pure Rust)
image = "0.25"

[[bin]]
name = "nu_plugin_image"
path = "src/main.rs"
bench = false
